### ISSUE TITLE
Needs to be updated for NA

### ISSUE THREAD

**Issue by celnu** [Shinoyx/rk9guide#10]
Needs to be updated for NA, it's not working for me.

**Comment by Shinoyx** [comment]
Did you try updating this script by downloading the latest? As well as update your proxy folder through pinkie's latest proxy version for NA. 

If that did not solve your issue, could you explain more on what is not working as well as provide some screenshots.

**Comment by celnu** [comment]
Hello! It works now, i forgot to update proxy! However i did notice that on last boss the calls out are not always correct. Thank you for your mod and for responding quickly. :)

**Comment by Shinoyx** [comment]
I did receive feedbacks about that issue. But can't seem to trigger it with my runs to log it... 
Will need more time to do testing. In the mean time if you ran into that bug again, it would be great if you could help me get a video of it. Thanks

**Comment by celnu** [comment]
It's mostly just that the call outs are backwards. For example the mech will be In + Out but the mod will show it as Out + In. I'll try and record a video for you!

**Comment by Shinoyx** [comment]
Oh... it was meant to do that. For example boss doing IN+OUT means he will hit inner then outer.
It calls what the boss is doing and **NOT** safe zones

**Comment by jokisa95** [comment]
just change IN to OUT and vice versa,it will work as it should be working

**Comment by Shinoyx** [comment]
Anyway the script has been updated to do safe zone call outs instead of what he is doing. Download the latest and try again. If you face any issue or bug, you can pm me or open a ticket again.

**Comment by jokisa95** [comment]
works for self,for party notice its opposite
