### ISSUE TITLE
Failed to load 

### ISSUE THREAD

**Issue by CLBOM** [Shinoyx/rk9guide#11]
![failed to load](https://user-images.githubusercontent.com/34169582/33497272-885e8844-d6b4-11e7-8f0b-7201a663604d.png)

**Comment by CLBOM** [comment]
Also im on the NA server

**Comment by Combataccelerator** [comment]
same for me 
![screenshot_2](https://user-images.githubusercontent.com/29666265/33516779-cdd3d0d6-d778-11e7-9b9e-f6c2fb52e4b8.png)

**Comment by Combataccelerator** [comment]
Update pls :D

**Comment by celnu** [comment]
It works, you need to update your proxy again.

**Comment by CLBOM** [comment]
I did... Updated proxy and module. Still failing to load

**Comment by Shinoyx** [comment]
@CLBOM You are placing it in the wrong folder. Make sure its in tera-proxy/bin/node_modules/rk9guide/index.js

If you are still facing any issue, drop me a pm on discord.
