### ISSUE TITLE
Streamer friendly

### ISSUE THREAD

**Issue by Shinoyx** [Shinoyx/rk9guide#13]
Quite a few people requested. 
- Change party notice to use proxy chat only  to prevent messages from popping out on the middle of the screen.

This will be an add on command to current features to make the guide call out be in chat box only.

Progress: 0%

**Comment by Owyn** [comment]
> guide call out be in chat box only.

will it even be noticeable? I mean unlike notice it's not in the center and doesn't make a sound

**Comment by Shinoyx** [comment]
It will still be party notice by default. 

I plan to add a command !stream to change the call outs to be in chat box. 
Yes, it will be hardly noticeable but that's the point of that if you want to stream live on twitch with proxy.

**Comment by Shinoyx** [comment]
Added this function.
I have YET to test out. Would be thankful if anyone is willing to test this. 

Use '!stream' to enable this.
- Turned off all itemhelper on the ground
- All call outs are using the proxy chat on your chat box, nothing will pop up on your screen

Report to me if there is any issue.

**Comment by Shinoyx** [comment]
Added. Closed.
Feel free to contact me if there is any issue.
