### ISSUE TITLE
RKEM last boss wrong call

### ISSUE THREAD

**Issue by terarian** [Shinoyx/rk9guide#16]
Hi, this issue has happened several time, so I tried to figure out, but didn't get the issue solved.

For RKEM last boss, when the very first mech (In/Out/Wave) is "Wave", sometimes the guide says "In" instead. And after the 95% shield, if it is "Wave(guide says In tho) + 0" and then, "In" comes for the "0", it will say "In + In" which is wrong.

It only happens when the very first one is "Wave"

I am not good at JS, but I tried to edit the msg output in order to figure out what is wrong before asking you.

First, I switched msgs 'in' and 'out' each other so that the guide calls out where to go instead of which AOE happens. Second, I added numbers after the Msg (In/Out/Wave) in regular sequence just in case I can figure out which msg is a wrong call. Here's the screenshot how I edited;
http://puu.sh/yBa51/9d91518a47.png

And here is the example screenshot of the wrong call.
https://puu.sh/yB5e0/5e3c3fafb4.jpg

The very first one was "Wave", but the guide calls "OUT8" which is 8th 'OUT' in the script. And when the mechanic actually comes out, the triangle (underneath the boss) was green and the msg was "Melee" which I had to go out. So it should be "Wave + OUT"(remember I switched 'IN' & 'OUT'), but it says "OUT8 + OUT7"

Again, it only happens if the very first one is "Wave"

Could you fix this issue? I am not good at JS so I do not know how I can explain more.

Thanks in advance.

- Add - 

In my last run, the very first mech was "Wave" but the guide called it correctly this time. Well, the color underneath the boss was red at the begging and the guide said '0 + WAVE2' (take a look at the ss to see where WAVE2 is at).
http://puu.sh/yBbJV/7ce8e65e80.png

 And then the color turned into green, and it still correctly said Next : WAVE2+0, and everything was correct after all. Below is the SS of the proof.

http://puu.sh/yBbEF/6d5bd7779f.jpg

I still do not know why sometimes it calls OUT+OUT instead of WAVE+OUT and the wrong call is OUT8 instead of WAVE.

Hopefully you can figure out what is wrong :D

**Comment by Shinoyx** [comment]
Could you try downloading the latest without editing anything.

The newest version should be safe zone call outs already. There's no need in editing at all. 

I haven't run any EM at this point in time because i'm very busy with work and other stuff. I have also requested a few users to keep an eye out for me on this issue as well. If this issue still persist after using the newest version, it will be great if you can get a recording on it. Feel free to pm me on discord if you wish to discuss this privately.

**Comment by Owyn** [comment]
just got "IN + IN" in RKE lol, wtf?

full chat log:

`````
[Proxy] Welcome to RK-9 Hard Mode  Type !help for more info 
[Notice][DG-Guide] : Right →↘
[Notice][DG-Guide] : WAVE , OUT
[Notice][DG-Guide] : Left ←↙
[Notice][DG-Guide] : WAVE , OUT
[Notice][DG-Guide] : Right →↘
[Notice][DG-Guide] : SHIELD!
[Notice][DG-Guide] : IN , WAVE
[Notice][DG-Guide] : GET OUT ↓
[Notice][DG-Guide] : Left ←↙
[Notice][DG-Guide] : Right →↘
[Notice][DG-Guide] : IN , IN

`````

but all other times all was ok, and we finished it in the end. maybe server lag, no idea, other user in party had old version which was telling where it strikes and he said it wrote "IN + OUT" for him instead of mine "IN + IN"

**Comment by Shinoyx** [comment]
Hmm, I will consider to re-code everything to that mech from scratch. Cause I know the current script is abit inefficient.

**Comment by Mkalo** [comment]
This is not really a rare issue, it happens if you wipe and res inside, the initialize function doesnt get called and variables dont get reseted.

Just check if the boss's gameId changed and call initialize if it does on S_BOSS_GAGE

**Comment by Shinoyx** [comment]
@Mkalo Thanks for the info.
As there is new dungeons and new stuff happening on KR, I will not be active on this guide anymore.
Just added a simple initialize when bosshp is 100%. Not yet tested but should work :rofl:

**Comment by Shinoyx** [comment]
Should be fixed. Closed.
