### ISSUE TITLE
last: shield timer warning?

### ISSUE THREAD

**Issue by Owyn** [Shinoyx/rk9guide#17]
A warning message like "Shield in 10sec" would be great 👍

**Comment by Shinoyx** [comment]
I will consider that. I could only set a timer to call out when his shield is off cooldown. 
It will never be 100% accurate on what he will do next.

**Comment by Shinoyx** [comment]
Added in recent update. I have yet to test it out... might not be accurate.
It is set to countdown 100 sec after his initial shield cast.
*This notice WILL pop up if the boss cast a shield before he die. OR if your team wipe on the shield it will call out again after 100 sec

**Comment by Shinoyx** [comment]
Testing complete. Closed.

**Comment by Owyn** [comment]
> *This notice WILL pop up if the boss cast a shield before he die. OR if your team wipe on the shield it will call out again after 100 sec

don't you reset some things already on boss wipe\death\reentering dungeon? you could put clearTimeout there too

**Comment by Shinoyx** [comment]
@Owyn I have updated it. I have yet to test it out.
