### ISSUE TITLE
flower clarity

### ISSUE THREAD

**Issue by Owyn** [Shinoyx/rk9guide#2]
could you spawn like more slowers or smth? to make the outer line of attack more visible, cuz if boss turns even a little it's hard to notice where to go now

and move flowers a bit away, so they would be placed in safe zone 👍 
something of a corner shape would be ideal |_ - like two sign items making a corner to show a safe zone start shape

like this (red lines): 
![tera_screenshot_20171014_021552_proc](https://user-images.githubusercontent.com/1309656/31570784-7b52adf0-b090-11e7-84ff-04de64d7c8b3.jpg)

**Comment by Shinoyx** [comment]
I will take a look on this.

**Comment by Shinoyx** [comment]
@Owyn I have just updated to something like that. Only tested once. If there are any issues or if its not 100% accurate you can pm me :)

**Comment by Owyn** [comment]
those little flowers aren't clearly visible anyway ;s
but the main problem is that they spawn with a delay-lag usually (a bit after it already exploded):
![tera_screenshot_20171016_005234_proc](https://user-images.githubusercontent.com/1309656/31589600-edb637ea-b20c-11e7-879c-a79f053091af.jpg)

maybe you could use signs like in https://github.com/soler91/HH-Firewall-Markers ? those are high and visible enough and don't need that many spawns, just 4 I think

**Comment by Shinoyx** [comment]
@Owyn I haven't touched HH and not sure how the markers look like. A screenshot would be good :)

As for why there is a delay, is mainly cause there is slight chances that tank might move the boss before the punch goes down thus making it not 100% accurate. 

The flowers only appear when boss sets his fist on the ground and stopped moving, providing 100% accuracy. 

In conclusion, it is either you want accuracy or earlier prediction. This is also why I added the weed in advance to show general location if the tank **doesn't move**. Hope you understand ~

**Comment by Owyn** [comment]
Here's a video with those sings: https://www.youtube.com/watch?v=4jsy7oXBSZI 

so you're saying when you spawn big flowers it is still unknown where boss would strike accurately?
Anyway, waiting that long and showing little flowers AFTER it already killed you seems pretty not useful to me...

Yea, I've seen tank moving the boss while in this mechanic but it was one time

I'd like so along with big flowers it would show full patter of spawn items - if boss moves you can just move these along with boss instead of waiting for him to move to spawn these, that would be a good variant.

**Comment by NekoRetard** [comment]
I can't see dat arrow's o.o what need for see it?
And how disable the flowers? Only the notice Right or Left help so much. I dont need the flowers.

Nice job. :)

**Comment by Shinoyx** [comment]
@Kira98 The arrows should be call out by default together with LEFT or RIGHT. To turn off flowers just do !itemhelper command

 @Owyn Yea, the flowers won't be accurate if tank moves. Only when boss fully strikes down then it will be 100% accurate. Setting it any faster will cause it to be slightly off. The accuracy of the flowers will be a huge cause death when RK9 hard mode hits NA as there will be double S. You have to judge ahead upon the call out, then shift accordingly to the 2nd spawn of flowers.

All in all, if I set the flowers to spawn faster and the tank moves ALOT to the side, then you can't blame the flowers for being not accurate. As for now, I made the flowers to spawn upon final strike and boss lock the skill to generate 100% accuracy. 

For the time being, I will take a look at the HH markers and see what I can do.

**Comment by NekoRetard** [comment]
T_T I can't see the arrow, just see a Box. Do I need a font or something? ._.

**Comment by Shinoyx** [comment]
@Kira98 Yes I have notice that problem on NA.. the arrow appears in KR but not for NA. When I have time I will look into arrow symbols to see if it works and update the script if needed.

**Comment by Owyn** [comment]
RU also shows arrows fine

**Comment by Shinoyx** [comment]
Probably NA server doesn't recognize that symbol...

**Comment by fortunefavor** [comment]
Try:

Navigate to the TERA\Client\S1Game\Localization\USA folder.
Rename the GFxUI into something else.
Going up one folder and enter the INT folder.
Copy both files from there and paste them into the USA folder.
Rename the ExampleGame.int and GFxUI.int into ExampleGame.usa and GFxUI.usa, respectively.

Your in game font will change but the arrows will show. This also improves font size so you don't squint while reading stuff in game lol.

**Comment by Shinoyx** [comment]
After so long, I don't think I have the intention of changing the item spawns to HH markers or anything like that. HH firewalls isn't as fast as RK9 SBOMB and the placement for it is rather stationary as compared to RK9 SBOMB. 

 As a matter of fact, the hit area of SBOMB is very so dependent on the tank. If tank moves him even the slightest, the markings would change. You just have to play by experience. 

 Hope you understand and thanks for the suggestion. Closed.
