### ISSUE TITLE
!lastbosstoparty not working properly at all

### ISSUE THREAD

**Issue by ghost** [Shinoyx/rk9guide#20]
all in title

**Comment by Shinoyx** [comment]
I did test this on KR previously like 2months ago and it worked perfectly. Haven't test this out on NA / EU. Will take a look if I have the time.

Will you also give more description on what is not working? The command? The function giving wrong mechs or the function not giving any message at all.

**Comment by Shinoyx** [comment]
Double confirmed it is working on KR. If you are still facing issue, open a new ticket, provide me with some screenshots and more details.
