### ISSUE TITLE
New guide

### ISSUE THREAD

**Issue by dozych** [Shinoyx/rk9guide#24]
hi. u can made rmhm guide similar to rk9guide?

**Comment by Owyn** [comment]
someone in teramods discord said he's already making one...
btw, why do ppl need a module for boss without complex mechanics?

**Comment by dozych** [comment]
i have not stable ping on eu servers, very need for last boss mechanics similar module ^_^

**Comment by Shinoyx** [comment]
Honestly rmhm isn't hard... I don't see a need for a guide for that dungeon. 

People are too used to being carried by a guide. Everyone needa run rk9 extreme without my guide to understand the amount of wipes and the inability to read Korean while I was making that guide -.-

I don't mind making a guide for it depending on the public's response.

**Comment by Owyn** [comment]
> rmhm isn't hard
> depending on the public's response.

could you make a guide for HarrowHold 4phase then? at least for colored paws when he turns head

**Comment by Shinoyx** [comment]
As disappointing as it is, I have zero experience on harrowhold. Plus no Korean players would want someone who can't read Korean in their raid. Another issue is I'm playing on CH the population is dead to even run HH.

**Comment by russopie** [comment]
Come to Pixar's raid whe have 3 raids atm running HH every week

**Comment by 256dot16hypen** [comment]
how can i join pixar's raid ? @@
me and my friend have frostmetal + daylight equipment (Warrior and Priest Class) @russopie

**Comment by Shinoyx** [comment]
Closed old thread. Will not be releasing any guide for Red Refuge or Antaros illusion. I am however looking into the upcoming newest dungeon in KR Tenebris Citadel 12 July and Rihanna's Underground hall 19 July. No promises.
