### ISSUE TITLE
Completely broken (endless calls spam)

### ISSUE THREAD

**Issue by P-r-o-x-y** [Shinoyx/rk9guide#28]
Hi the guide ended up pretty broken. Missing regular first boss calls with a light spam of wind calls, the second boss miss all the few calls there was and the third boss (tested only on extreme mode) is a endless spam of the 70% Hp boss call during all the boss fight. Hope you will give it at look o/

**Comment by Shinoyx** [comment]
I just updated it. Help to check and see if it is fixed.

**Comment by P-r-o-x-y** [comment]
Tested in RK9 extreme mode and works perfectly 👍
