### ISSUE TITLE
Notices

### ISSUE THREAD

**Issue by patopatopingu** [Shinoyx/rk9guide#3]
I know you can disable certain bosses in the file, but is there some way to disable the notices altogether (without removing the message) and just make it... I don't know really. A message in proxy like the welcome message? Or a whisper? Something other than a big notice in the middle of the screen. Just a tiny idea and nbd if it can't be done/not worth the time. <3 thanks!!

**Comment by Shinoyx** [comment]
@patopatopingu  Yes you can actually change it to show like welcome message. Just do the following to your rk9 index.js from around line 650-653:
<img src="https://cdn.discordapp.com/attachments/336110092170690560/375836081008017411/unknown.png">

* Take note to backup a copy. Im not doing RK9 anytime soon to test it out.
