### ISSUE TITLE
add messages for new HM\EX mechanics please?

### ISSUE THREAD

**Issue by Owyn** [Shinoyx/rk9guide#7]
The one which you should remember what was the last attack cuz it'll become the next (HM) and write into notice "RANGED, WAVE" or "Melee, Ranged",

and for EX write it when he swaps em.

https://www.youtube.com/watch?v=2xbmIPGDXa4

**Comment by Owyn** [comment]
how come you had those long ago when there was no hard version available anywhere? O_o

**Comment by Shinoyx** [comment]
@Owyn I had it scripted out long ago during my runs on KR server. I played both KR and NA servers.
