### ISSUE TITLE
Problems making it work

### ISSUE THREAD

**Issue by Coniflex** [Shinoyx/rk9guide#8]
The module seems to run fine when i start the game up and when I enter RK9 aswell, but i can't use any of the commands. 
![half working](https://user-images.githubusercontent.com/33980278/33230101-4b142f74-d1dd-11e7-85d4-bd80a08633a3.png)

I updated my tera-data and got the newest proxy, but i'm not sure what's going wrong.
I dont have a screenshot of the errors right now but i'll post them as soon as i can.

Kind regards.

-edit here is the error
![image](https://user-images.githubusercontent.com/33980278/33233505-244c75c4-d217-11e7-8ecb-8395f8611fa3.png)

**Comment by Shinoyx** [comment]
Download the latest version and update your proxy with the latest version pinkie sent.
