### ISSUE TITLE
Out In on HM

### ISSUE THREAD

**Issue by SoCen** [Shinoyx/rk9guide#9]
When it says OUT in Hm, does that mean the damage will be on the outside and you have to stay in ?
Also when it says IN, it seems like the damage is on the inside.
Like, message such as Get out & Wave would make sense.

**Comment by Shinoyx** [comment]
It calls on what is going to come. 
Example IN+OUT will be doing inner then outer circle 
Same goes for IN+WAVE will be doing inner attack then wave attacks

**Comment by jokisa95** [comment]
is there any way to change that?
